/**
 * Created by Jared on 16/3/3.
 */
 //home
export const GET_PROTECT_INFO = 'GET_PROTECT_INFO';
export const SET_INFO_USE = 'SET_INFO_USE';
export const GET_INFO_USE = 'GET_INFO_USE';
export const SET_INFO_LOCK = 'SET_INFO_LOCK';
export const GET_INFO_LOCK = 'GET_INFO_LOCK';

export const SET_STUDY_MODEL_APP = 'SET_STUDY_MODEL_APP';
export const SET_STUDY_MODEL = 'SET_STUDY_MODEL';
export const SET_MANAGE_MODEL = 'SET_MANAGE_MODEL';
export const GET_MANAGE_STUDY_STATUS = 'GET_MANAGE_STUDY_STATUS';
export const SET_MANAGE_MODEL_APP = "SET_MANAGE_MODEL_APP";

export const GET_APP_SCALE = "GET_APP_SCALE";
export const GET_MULTIVARIATE = "GET_MULTIVARIATE";
export const GET_MULTIVARIATE_APP = "GET_MULTIVARIATE_APP";
export const GET_CHILND_INFO = "GET_CHILND_INFO";